// Copyright 2025 Hajime Hoshi
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !android && !ios && !js && !nintendosdk && !playstation5

package ui

import (
	"github.com/hajimehoshi/ebiten/v2/internal/glfw"
)

var glfwKeyToUIKey = map[glfw.Key]Key{
	glfw.KeyA:            KeyA,
	glfw.KeyLeftAlt:      KeyAltLeft,
	glfw.KeyRightAlt:     KeyAltRight,
	glfw.KeyDown:         KeyArrowDown,
	glfw.KeyLeft:         KeyArrowLeft,
	glfw.KeyRight:        KeyArrowRight,
	glfw.KeyUp:           KeyArrowUp,
	glfw.KeyB:            KeyB,
	glfw.KeyGraveAccent:  KeyBackquote,
	glfw.KeyBackslash:    KeyBackslash,
	glfw.KeyBackspace:    KeyBackspace,
	glfw.KeyLeftBracket:  KeyBracketLeft,
	glfw.KeyRightBracket: KeyBracketRight,
	glfw.KeyC:            KeyC,
	glfw.KeyCapsLock:     KeyCapsLock,
	glfw.KeyComma:        KeyComma,
	glfw.KeyMenu:         KeyContextMenu,
	glfw.KeyLeftControl:  KeyControlLeft,
	glfw.KeyRightControl: KeyControlRight,
	glfw.KeyD:            KeyD,
	glfw.KeyDelete:       KeyDelete,
	glfw.Key0:            KeyDigit0,
	glfw.Key1:            KeyDigit1,
	glfw.Key2:            KeyDigit2,
	glfw.Key3:            KeyDigit3,
	glfw.Key4:            KeyDigit4,
	glfw.Key5:            KeyDigit5,
	glfw.Key6:            KeyDigit6,
	glfw.Key7:            KeyDigit7,
	glfw.Key8:            KeyDigit8,
	glfw.Key9:            KeyDigit9,
	glfw.KeyE:            KeyE,
	glfw.KeyEnd:          KeyEnd,
	glfw.KeyEnter:        KeyEnter,
	glfw.KeyEqual:        KeyEqual,
	glfw.KeyEscape:       KeyEscape,
	glfw.KeyF:            KeyF,
	glfw.KeyF1:           KeyF1,
	glfw.KeyF10:          KeyF10,
	glfw.KeyF11:          KeyF11,
	glfw.KeyF12:          KeyF12,
	glfw.KeyF13:          KeyF13,
	glfw.KeyF14:          KeyF14,
	glfw.KeyF15:          KeyF15,
	glfw.KeyF16:          KeyF16,
	glfw.KeyF17:          KeyF17,
	glfw.KeyF18:          KeyF18,
	glfw.KeyF19:          KeyF19,
	glfw.KeyF2:           KeyF2,
	glfw.KeyF20:          KeyF20,
	glfw.KeyF21:          KeyF21,
	glfw.KeyF22:          KeyF22,
	glfw.KeyF23:          KeyF23,
	glfw.KeyF24:          KeyF24,
	glfw.KeyF3:           KeyF3,
	glfw.KeyF4:           KeyF4,
	glfw.KeyF5:           KeyF5,
	glfw.KeyF6:           KeyF6,
	glfw.KeyF7:           KeyF7,
	glfw.KeyF8:           KeyF8,
	glfw.KeyF9:           KeyF9,
	glfw.KeyG:            KeyG,
	glfw.KeyH:            KeyH,
	glfw.KeyHome:         KeyHome,
	glfw.KeyI:            KeyI,
	glfw.KeyInsert:       KeyInsert,
	glfw.KeyWorld1:       KeyIntlBackslash,
	glfw.KeyJ:            KeyJ,
	glfw.KeyK:            KeyK,
	glfw.KeyL:            KeyL,
	glfw.KeyM:            KeyM,
	glfw.KeyLeftSuper:    KeyMetaLeft,
	glfw.KeyRightSuper:   KeyMetaRight,
	glfw.KeyMinus:        KeyMinus,
	glfw.KeyN:            KeyN,
	glfw.KeyNumLock:      KeyNumLock,
	glfw.KeyKP0:          KeyNumpad0,
	glfw.KeyKP1:          KeyNumpad1,
	glfw.KeyKP2:          KeyNumpad2,
	glfw.KeyKP3:          KeyNumpad3,
	glfw.KeyKP4:          KeyNumpad4,
	glfw.KeyKP5:          KeyNumpad5,
	glfw.KeyKP6:          KeyNumpad6,
	glfw.KeyKP7:          KeyNumpad7,
	glfw.KeyKP8:          KeyNumpad8,
	glfw.KeyKP9:          KeyNumpad9,
	glfw.KeyKPAdd:        KeyNumpadAdd,
	glfw.KeyKPDecimal:    KeyNumpadDecimal,
	glfw.KeyKPDivide:     KeyNumpadDivide,
	glfw.KeyKPEnter:      KeyNumpadEnter,
	glfw.KeyKPEqual:      KeyNumpadEqual,
	glfw.KeyKPMultiply:   KeyNumpadMultiply,
	glfw.KeyKPSubtract:   KeyNumpadSubtract,
	glfw.KeyO:            KeyO,
	glfw.KeyP:            KeyP,
	glfw.KeyPageDown:     KeyPageDown,
	glfw.KeyPageUp:       KeyPageUp,
	glfw.KeyPause:        KeyPause,
	glfw.KeyPeriod:       KeyPeriod,
	glfw.KeyPrintScreen:  KeyPrintScreen,
	glfw.KeyQ:            KeyQ,
	glfw.KeyApostrophe:   KeyQuote,
	glfw.KeyR:            KeyR,
	glfw.KeyS:            KeyS,
	glfw.KeyScrollLock:   KeyScrollLock,
	glfw.KeySemicolon:    KeySemicolon,
	glfw.KeyLeftShift:    KeyShiftLeft,
	glfw.KeyRightShift:   KeyShiftRight,
	glfw.KeySlash:        KeySlash,
	glfw.KeySpace:        KeySpace,
	glfw.KeyT:            KeyT,
	glfw.KeyTab:          KeyTab,
	glfw.KeyU:            KeyU,
	glfw.KeyV:            KeyV,
	glfw.KeyW:            KeyW,
	glfw.KeyX:            KeyX,
	glfw.KeyY:            KeyY,
	glfw.KeyZ:            KeyZ,
}
